// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2gTEOcOB2JGP2n3LlCWeSTPSIJyQoKRw',
    appId: '1:850266585346:web:a14fabbea56598966a6a1b',
    messagingSenderId: '850266585346',
    projectId: 'questionba-a3e9a',
    authDomain: 'questionba-a3e9a.firebaseapp.com',
    storageBucket: 'questionba-a3e9a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3kIkTDNDNF4Ix91SmmodHusaqKWaaw5E',
    appId: '1:850266585346:android:157ecdf6accdbc606a6a1b',
    messagingSenderId: '850266585346',
    projectId: 'questionba-a3e9a',
    storageBucket: 'questionba-a3e9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZVez6E12Vgv_ArtsPmdEsoT_-UOdR18g',
    appId: '1:850266585346:ios:c34820de57f4d31a6a6a1b',
    messagingSenderId: '850266585346',
    projectId: 'questionba-a3e9a',
    storageBucket: 'questionba-a3e9a.appspot.com',
    iosClientId: '850266585346-qg64lanroe5to8g48os17l8r28df1tkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.questionbank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZVez6E12Vgv_ArtsPmdEsoT_-UOdR18g',
    appId: '1:850266585346:ios:c34820de57f4d31a6a6a1b',
    messagingSenderId: '850266585346',
    projectId: 'questionba-a3e9a',
    storageBucket: 'questionba-a3e9a.appspot.com',
    iosClientId: '850266585346-qg64lanroe5to8g48os17l8r28df1tkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.questionbank',
  );
}
