class Autogenerated {
  AerospaceEngineering? aerospaceEngineering;
  AerospaceEngineering? agriculturalEngineering;
  ArchitectureEngineering? architectureEngineering;
  AutomobileEngineering? automobileEngineering;
  AutomobileEngineering? civilEngineering;
  ComputerEngineering? computerEngineering;
  ComputerEngineering? electricalEnginerring;
  ComputerEngineering? electronicsCommunicationEngineering;
  ComputerEngineering? geomaticsEngineering;
  AerospaceEngineering? industrialEngineering;
  AerospaceEngineering? mechanicalEngineering;

  Autogenerated(
      {this.aerospaceEngineering,
      this.agriculturalEngineering,
      this.architectureEngineering,
      this.automobileEngineering,
      this.civilEngineering,
      this.computerEngineering,
      this.electricalEnginerring,
      this.electronicsCommunicationEngineering,
      this.geomaticsEngineering,
      this.industrialEngineering,
      this.mechanicalEngineering});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    aerospaceEngineering = json['Aerospace_Engineering'] != null
        ? new AerospaceEngineering.fromJson(json['Aerospace_Engineering'])
        : null;
    agriculturalEngineering = json['Agricultural_Engineering'] != null
        ? new AerospaceEngineering.fromJson(json['Agricultural_Engineering'])
        : null;
    architectureEngineering = json['Architecture_Engineering'] != null
        ? new ArchitectureEngineering.fromJson(json['Architecture_Engineering'])
        : null;
    automobileEngineering = json['Automobile Engineering'] != null
        ? new AutomobileEngineering.fromJson(json['Automobile Engineering'])
        : null;
    civilEngineering = json['Civil Engineering'] != null
        ? new AutomobileEngineering.fromJson(json['Civil Engineering'])
        : null;
    computerEngineering = json['Computer Engineering'] != null
        ? new ComputerEngineering.fromJson(json['Computer Engineering'])
        : null;
    electricalEnginerring = json['Electrical Enginerring'] != null
        ? new ComputerEngineering.fromJson(json['Electrical Enginerring'])
        : null;
    electronicsCommunicationEngineering =
        json['Electronics & Communication Engineering'] != null
            ? new ComputerEngineering.fromJson(
                json['Electronics & Communication Engineering'])
            : null;
    geomaticsEngineering = json['Geomatics Engineering'] != null
        ? new ComputerEngineering.fromJson(json['Geomatics Engineering'])
        : null;
    industrialEngineering = json['Industrial Engineering'] != null
        ? new AerospaceEngineering.fromJson(json['Industrial Engineering'])
        : null;
    mechanicalEngineering = json['Mechanical Engineering'] != null
        ? new AerospaceEngineering.fromJson(json['Mechanical Engineering'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.aerospaceEngineering != null) {
      data['Aerospace_Engineering'] = this.aerospaceEngineering!.toJson();
    }
    if (this.agriculturalEngineering != null) {
      data['Agricultural_Engineering'] = this.agriculturalEngineering!.toJson();
    }
    if (this.architectureEngineering != null) {
      data['Architecture_Engineering'] = this.architectureEngineering!.toJson();
    }
    if (this.automobileEngineering != null) {
      data['Automobile Engineering'] = this.automobileEngineering!.toJson();
    }
    if (this.civilEngineering != null) {
      data['Civil Engineering'] = this.civilEngineering!.toJson();
    }
    if (this.computerEngineering != null) {
      data['Computer Engineering'] = this.computerEngineering!.toJson();
    }
    if (this.electricalEnginerring != null) {
      data['Electrical Enginerring'] = this.electricalEnginerring!.toJson();
    }
    if (this.electronicsCommunicationEngineering != null) {
      data['Electronics & Communication Engineering'] =
          this.electronicsCommunicationEngineering!.toJson();
    }
    if (this.geomaticsEngineering != null) {
      data['Geomatics Engineering'] = this.geomaticsEngineering!.toJson();
    }
    if (this.industrialEngineering != null) {
      data['Industrial Engineering'] = this.industrialEngineering!.toJson();
    }
    if (this.mechanicalEngineering != null) {
      data['Mechanical Engineering'] = this.mechanicalEngineering!.toJson();
    }
    return data;
  }
}

class AerospaceEngineering {
  List<String>? l1stSemester;
  List<String>? l2ndSemester;
  List<String>? l3rdSemester;
  List<String>? l4thSemester;
  List<String>? l5thSemester;
  List<String>? l6thSemester;
  List<String>? l7thSemester;
  List<String>? l8thSemester;

  AerospaceEngineering(
      {this.l1stSemester,
      this.l2ndSemester,
      this.l3rdSemester,
      this.l4thSemester,
      this.l5thSemester,
      this.l6thSemester,
      this.l7thSemester,
      this.l8thSemester});

  AerospaceEngineering.fromJson(Map<String, dynamic> json) {
    l1stSemester = json['1st_Semester'].cast<String>();
    l2ndSemester = json['2nd_Semester'].cast<String>();
    l3rdSemester = json['3rd_Semester'].cast<String>();
    l4thSemester = json['4th_Semester'].cast<String>();
    l5thSemester = json['5th_Semester'].cast<String>();
    l6thSemester = json['6th_Semester'].cast<String>();
    l7thSemester = json['7th_Semester'].cast<String>();
    l8thSemester = json['8th_Semester'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['1st_Semester'] = this.l1stSemester;
    data['2nd_Semester'] = this.l2ndSemester;
    data['3rd_Semester'] = this.l3rdSemester;
    data['4th_Semester'] = this.l4thSemester;
    data['5th_Semester'] = this.l5thSemester;
    data['6th_Semester'] = this.l6thSemester;
    data['7th_Semester'] = this.l7thSemester;
    data['8th_Semester'] = this.l8thSemester;
    return data;
  }
}

class ArchitectureEngineering {
  List<String>? l1stSemester;
  List<String>? l2ndSemester;
  List<String>? l3rdSemester;
  List<String>? l4thSemester;
  List<String>? l5thSemester;
  List<String>? l6thSemester;
  List<String>? l7ThSemester;
  List<String>? l8thSemester;
  List<String>? l9ThSemester;
  List<String>? l10ThSemester;

  ArchitectureEngineering(
      {this.l1stSemester,
      this.l2ndSemester,
      this.l3rdSemester,
      this.l4thSemester,
      this.l5thSemester,
      this.l6thSemester,
      this.l7ThSemester,
      this.l8thSemester,
      this.l9ThSemester,
      this.l10ThSemester});

  ArchitectureEngineering.fromJson(Map<String, dynamic> json) {
    l1stSemester = json['1st_Semester'].cast<String>();
    l2ndSemester = json['2nd_Semester'].cast<String>();
    l3rdSemester = json['3rd_Semester'].cast<String>();
    l4thSemester = json['4th_Semester'].cast<String>();
    l5thSemester = json['5th_Semester'].cast<String>();
    l6thSemester = json['6th_Semester'].cast<String>();
    l7ThSemester = json['7_thSemester'].cast<String>();
    l8thSemester = json['8th_Semester'].cast<String>();
    l9ThSemester = json['9_thSemester'].cast<String>();
    l10ThSemester = json['10_thSemester'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['1st_Semester'] = this.l1stSemester;
    data['2nd_Semester'] = this.l2ndSemester;
    data['3rd_Semester'] = this.l3rdSemester;
    data['4th_Semester'] = this.l4thSemester;
    data['5th_Semester'] = this.l5thSemester;
    data['6th_Semester'] = this.l6thSemester;
    data['7_thSemester'] = this.l7ThSemester;
    data['8th_Semester'] = this.l8thSemester;
    data['9_thSemester'] = this.l9ThSemester;
    data['10_thSemester'] = this.l10ThSemester;
    return data;
  }
}

class AutomobileEngineering {
  List<String>? l1stSemester;
  List<String>? l2ndSemester;
  List<String>? l3rdSemester;
  List<String>? l4thSemester;
  List<String>? l5thSemester;
  List<String>? l6thSemester;
  List<String>? l7ThSemester;
  List<String>? l8thSemester;

  AutomobileEngineering(
      {this.l1stSemester,
      this.l2ndSemester,
      this.l3rdSemester,
      this.l4thSemester,
      this.l5thSemester,
      this.l6thSemester,
      this.l7ThSemester,
      this.l8thSemester});

  AutomobileEngineering.fromJson(Map<String, dynamic> json) {
    l1stSemester = json['1st_Semester'].cast<String>();
    l2ndSemester = json['2nd_Semester'].cast<String>();
    l3rdSemester = json['3rd_Semester'].cast<String>();
    l4thSemester = json['4th_Semester'].cast<String>();
    l5thSemester = json['5th_Semester'].cast<String>();
    l6thSemester = json['6th_Semester'].cast<String>();
    l7ThSemester = json['7_thSemester'].cast<String>();
    l8thSemester = json['8th_Semester'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['1st_Semester'] = this.l1stSemester;
    data['2nd_Semester'] = this.l2ndSemester;
    data['3rd_Semester'] = this.l3rdSemester;
    data['4th_Semester'] = this.l4thSemester;
    data['5th_Semester'] = this.l5thSemester;
    data['6th_Semester'] = this.l6thSemester;
    data['7_thSemester'] = this.l7ThSemester;
    data['8th_Semester'] = this.l8thSemester;
    return data;
  }
}

class ComputerEngineering {
  List<String>? l1stSemester;
  List<String>? l2ndSemester;
  List<String>? l3rdSemester;
  List<String>? l4thSemester;
  List<String>? l5ThSemester;
  List<String>? l6thSemester;
  List<String>? l7ThSemester;
  List<String>? l8thSemester;

  ComputerEngineering(
      {this.l1stSemester,
      this.l2ndSemester,
      this.l3rdSemester,
      this.l4thSemester,
      this.l5ThSemester,
      this.l6thSemester,
      this.l7ThSemester,
      this.l8thSemester});

  ComputerEngineering.fromJson(Map<String, dynamic> json) {
    l1stSemester = json['1st_Semester'].cast<String>();
    l2ndSemester = json['2nd_Semester'].cast<String>();
    l3rdSemester = json['3rd_Semester'].cast<String>();
    l4thSemester = json['4th_Semester'].cast<String>();
    l5ThSemester = json['5_thSemester'].cast<String>();
    l6thSemester = json['6th_Semester'].cast<String>();
    l7ThSemester = json['7_thSemester'].cast<String>();
    l8thSemester = json['8th_Semester'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['1st_Semester'] = this.l1stSemester;
    data['2nd_Semester'] = this.l2ndSemester;
    data['3rd_Semester'] = this.l3rdSemester;
    data['4th_Semester'] = this.l4thSemester;
    data['5_thSemester'] = this.l5ThSemester;
    data['6th_Semester'] = this.l6thSemester;
    data['7_thSemester'] = this.l7ThSemester;
    data['8th_Semester'] = this.l8thSemester;
    return data;
  }
}
